package br.com.estudo.pagamentos.usuario;

public enum Papel {
    ADMINISTRAR_CONTAS_GERENCIAIS, ADMINISTRAR_CENTROS_DE_CUSTO, ADMINISTRAR_FORNECEDORES,
    APROVAR_SOLICITACAO_DE_PAGAMENTO_EM_EXCECAO, APROVAR_SOLICITACAO_DE_PAGAMENTO,
    SOLICITAR_PAGAMENTO
}
